version: '3'

services:
  laravel-docker:
    container_name: onfly_app
    entrypoint: dockerize -wait tcp://mysql_db:3307 -timeout 20s php artisan serve --host=0.0.0.0 --port=8000
    build: .
    volumes:
      - ./api_onfly:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
      - redis
    networks:
    - onfly-network

  redis:
    container_name: onfly_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
    - onfly-network

  mysql_db:
    container_name: onfly_database
    image: mysql:latest
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onfly
      MYSQL_USER: api_onfly
      MYSQL_PASSWORD: '04Ch}fF1QjZpc8QK&gzL'
    ports:
      - 3307:3306
    networks:
    - onfly-network

networks:
  onfly-network:
    driver: "bridge"